name: Polycyclic
version: 2.13
date: 2018-04-26
description: |
    Computation with polycyclic groups

authors:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/
    - name: Max Horn
      url: http://www.quendi.de/math

maintainers:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.7"

needed-pkgs:
    - name: "alnuth"
      version: "3.0"
      url: "https://gap-packages.github.io/alnuth"
    - name: "autpgrp"
      version: "1.6"
      url: "https://gap-packages.github.io/autpgrp/"

www: https://gap-packages.github.io/polycyclic/
readme: README
packageinfo: https://gap-packages.github.io/polycyclic/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/polycyclic/releases/download/v2.13/polycyclic-2.13.tar.gz

abstract: |
    This package provides various algorithms for computations with polycyclic groups defined by polycyclic presentations.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
