name: Polycyclic
version: 2.11
date: 2013-03-07
description: |
    Computation with polycyclic groups

authors:
    - name: Bettina Eick
      url: mailto:beick@tu-bs.de
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/
    - name: Max Horn
      url: http://www.quendi.de/math.php

maintainers:
    - name: Bettina Eick
      url: mailto:beick@tu-bs.de
    - name: Max Horn
      url: http://www.quendi.de/math.php

GAP: ">= 4.5"

needed-pkgs:
    - name: "alnuth"
      version: "1.0"
      url: "https://gap-packages.github.io/alnuth"
    - name: "autpgrp"
      version: "1.4"
      url: "http://www.icm.tu-bs.de/~beick/so.html"

www: http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/
readme: README
packageinfo: http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/polycyclic-2.11.tar.gz
    - name: .tar.bz2
      url: http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/polycyclic-2.11.tar.bz2

abstract: |
    This package provides various algorithms for computations with polycyclic groups defined by polycyclic presentations.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
